# Generated by Django 4.1.3 on 2023-03-27 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_app', '0003_order_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='favourite',
        ),
        migrations.AddField(
            model_name='order',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
