# Generated by Django 4.1.3 on 2023-03-27 14:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('order_app', '0004_remove_order_favourite_order_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
